<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pits_wd_calender"
 *
 * Auto generated by Extension Builder 2016-04-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Event Calender',
	'description' => 'Event Calender:This extension can be used to display events in a specified area with the help of Google map.The extension allows to enter the events from the back-end and front end.Also detailed view of each event is possible using this extension.The events can be categorized into regions based on there geographical location.The plug-in provides option to filter events based on region in the map.This extension can be used as simple map in the FE.For queries and bug reporting please feel free to conatct through email at abin.s@pitsolutions.com.',
	'category' => 'plugin',
	'author' => 'Abin Sabu, Ebin Mathew',
	'author_email' => 'abin.s@pitsolutions.com, ebin.cm@pitsolutions.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '6.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);